### ISSUE TITLE
Ceiling Fan: No Response and Log Errors

### ISSUE THREAD

**Issue by mkormendy** [XenuIsWatching/homebridge-hubspace#3]
I'm seeing a Ceiling Fan issue with the status of "No Response" on the tile in HomeKit. How do I fix this?

I'm seeing the following error in the homebridge logs:
```
[8/28/2024, 1:59:38 PM] [@xenuiswatching/homebridge-hubspace] This plugin threw an error from the characteristic 'Active': Unhandled error thrown inside read handler for characteristic: Failed to get function definition for 'fan-power'. Each function requires to set a definition.. See https://homebridge.io/w/JtMGR for more info.
[8/28/2024, 1:59:38 PM] [@xenuiswatching/homebridge-hubspace] Error: Failed to get function definition for 'fan-power'. Each function requires to set a definition.
    at getDeviceFunctionDef (/usr/local/lib/node_modules/@xenuiswatching/homebridge-hubspace/src/models/device-functions.ts:110:15)
    at FanAccessory.getActive (/usr/local/lib/node_modules/@xenuiswatching/homebridge-hubspace/src/accessories/fan-accessory.ts:50:42)
[8/28/2024, 1:59:38 PM] [@xenuiswatching/homebridge-hubspace] This plugin threw an error from the characteristic 'Color Temperature': Unhandled error thrown inside read handler for characteristic: Failed to get function definition for 'color-mode'. Each function requires to set a definition.. See https://homebridge.io/w/JtMGR for more info.
[8/28/2024, 1:59:38 PM] [@xenuiswatching/homebridge-hubspace] Error: Failed to get function definition for 'color-mode'. Each function requires to set a definition.
    at getDeviceFunctionDef (/usr/local/lib/node_modules/@xenuiswatching/homebridge-hubspace/src/models/device-functions.ts:110:15)
    at LightAccessory.getTemperature (/usr/local/lib/node_modules/@xenuiswatching/homebridge-hubspace/src/accessories/light-accessory.ts:138:42)
    at ColorTemperature.getHandler (/usr/local/lib/node_modules/@xenuiswatching/homebridge-hubspace/src/accessories/light-accessory.ts:62:31)
``` 

Hubspace Plugin Version: 2.1.2
Homebridge Version: 1.8.4
Homebridge UI Config X Version: 4.57.1
Node JS Version: 20.11.1

**Comment by town3r** [comment]
I'm getting the same error.

Also I'm not sure if it matters, but my fan model only has 3 speeds vs 6 like the one mentioned as a supported device.

Light temperature options: 2700K,3000K,3500K,4000K,5000K,6500K

https://www.homedepot.com/p/Hampton-Bay-Nevali-52-in-White-Changing-LED-Indoor-Smart-Hubspace-Ceiling-Fan-with-Light-and-Remote-Control-Included-92394/322700723

**Comment by town3r** [comment]
@XenuIsWatching Are you able to help with this plugin still?

**Comment by emtz1977** [comment]
@XenuIsWatching any luck fixing the fan issue?

**Comment by spectocr** [comment]
Doesn't look like this plugin is supported anymore, shame. Worked for a long time. Having same issue with fan.
